-- MySQL Script generated by MySQL Workbench
-- Wed May 16 21:29:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aocx
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aocx` ;

-- -----------------------------------------------------
-- Schema aocx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aocx` DEFAULT CHARACTER SET utf8 ;
USE `aocx` ;

-- -----------------------------------------------------
-- Table `aocx`.`distribute_uid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`distribute_uid` ;

CREATE TABLE IF NOT EXISTS `aocx`.`distribute_uid` (
  `id` INT NOT NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aocx`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`user` ;

CREATE TABLE IF NOT EXISTS `aocx`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `username` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` TINYTEXT NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `userid_idx` (`userid` ASC),
  UNIQUE INDEX `userid_UNIQUE` (`userid` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aocx`.`user_login_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`user_login_info` ;

CREATE TABLE IF NOT EXISTS `aocx`.`user_login_info` (
  `userid` INT NOT NULL,
  `login_times` INT(11) NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aocx`.`user_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`user_ticket` ;

CREATE TABLE IF NOT EXISTS `aocx`.`user_ticket` (
  `userid` INT NOT NULL,
  `key` VARCHAR(32) NOT NULL,
  `iv` VARCHAR(16) NOT NULL,
  `ticket` TINYTEXT NOT NULL,
  `ip` VARCHAR(64) NOT NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aocx`.`user_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`user_token` ;

CREATE TABLE IF NOT EXISTS `aocx`.`user_token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `token` VARCHAR(16) NOT NULL,
  `type` VARCHAR(8) NOT NULL,
  `create_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `userid_idx` (`userid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aocx`.`user_extra_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`user_extra_info` ;

CREATE TABLE IF NOT EXISTS `aocx`.`user_extra_info` (
  `userid` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `xuehao` VARCHAR(9) NULL,
  `site` VARCHAR(45) NULL,
  `bio` TINYTEXT NULL,
  `avatar` TINYTEXT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`problem` ;

CREATE TABLE IF NOT EXISTS `aocx`.`problem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TINYTEXT NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `url` TINYTEXT NOT NULL,
  `score` INT(6) NOT NULL,
  `level` INT(1) NOT NULL COMMENT '1-3简单\\4-6中等\\7-9困难',
  `category` VARCHAR(7) NOT NULL,
  `type` VARCHAR(8) NOT NULL COMMENT 'practice contest',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`problem_answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`problem_answer` ;

CREATE TABLE IF NOT EXISTS `aocx`.`problem_answer` (
  `pid` INT NOT NULL,
  `answer` TINYTEXT NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`problem_extra_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`problem_extra_info` ;

CREATE TABLE IF NOT EXISTS `aocx`.`problem_extra_info` (
  `pid` INT NOT NULL,
  `source` VARCHAR(45) NOT NULL DEFAULT '原创',
  `views` INT(11) NOT NULL DEFAULT 0,
  `participants` INT(11) NOT NULL DEFAULT 0,
  `post_times` INT(11) NOT NULL DEFAULT 0,
  `correct_times` INT(11) NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`practice_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`practice_post` ;

CREATE TABLE IF NOT EXISTS `aocx`.`practice_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `pid` INT NOT NULL,
  `answer` TINYTEXT NOT NULL,
  `create_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `userid_idx` (`userid` ASC),
  INDEX `pid_idx` (`pid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`practice_correct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`practice_correct` ;

CREATE TABLE IF NOT EXISTS `aocx`.`practice_correct` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `pid` INT NOT NULL,
  `score` INT(6) NOT NULL,
  `create_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `userid_idx` (`userid` ASC),
  INDEX `pid_idx` (`pid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`practice_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`practice_score` ;

CREATE TABLE IF NOT EXISTS `aocx`.`practice_score` (
  `userid` INT NOT NULL,
  `score` INT(11) NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`contest` ;

CREATE TABLE IF NOT EXISTS `aocx`.`contest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `type` VARCHAR(10) NOT NULL COMMENT 'individual个人赛、team团队赛',
  `status` INT(1) NOT NULL,
  `enroll_start_time` DATETIME NOT NULL,
  `enroll_end_time` DATETIME NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`contest_problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`contest_problem` ;

CREATE TABLE IF NOT EXISTS `aocx`.`contest_problem` (
  `cid` INT NOT NULL,
  `pid` INT NOT NULL,
  INDEX `pid_idx` (`pid` ASC),
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`user_contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`user_contest` ;

CREATE TABLE IF NOT EXISTS `aocx`.`user_contest` (
  `userid` INT NOT NULL,
  `cid` INT NOT NULL,
  `create_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  INDEX `userid_idx` (`userid` ASC),
  INDEX `cid_idx` (`cid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`contest_notice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`contest_notice` ;

CREATE TABLE IF NOT EXISTS `aocx`.`contest_notice` (
  `id` INT NOT NULL,
  `cid` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` TINYTEXT NOT NULL,
  `create_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `cid_idx` (`cid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`contest_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`contest_post` ;

CREATE TABLE IF NOT EXISTS `aocx`.`contest_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `pid` INT NOT NULL,
  `cid` INT NOT NULL,
  `answer` TINYTEXT NOT NULL,
  `create_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `userid_idx` (`userid` ASC),
  INDEX `pid_idx` (`pid` ASC),
  INDEX `cid_idx` (`cid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`contest_correct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`contest_correct` ;

CREATE TABLE IF NOT EXISTS `aocx`.`contest_correct` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `pid` INT NOT NULL,
  `cid` INT NOT NULL,
  `score` INT(6) NOT NULL,
  `create_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `userid_idx` (`userid` ASC),
  INDEX `pid_idx` (`pid` ASC),
  INDEX `cid_idx` (`cid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`contest_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`contest_score` ;

CREATE TABLE IF NOT EXISTS `aocx`.`contest_score` (
  `userid` INT NOT NULL,
  `cid` INT NOT NULL,
  `score` INT(11) NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  INDEX `userid_idx` (`userid` ASC),
  INDEX `cid_idx` (`cid` ASC),
  PRIMARY KEY (`userid`, `cid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aocx`.`contest_extra_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aocx`.`contest_extra_info` ;

CREATE TABLE IF NOT EXISTS `aocx`.`contest_extra_info` (
  `cid` INT NOT NULL,
  `organizer` VARCHAR(45) NOT NULL COMMENT '主办方',
  `place` VARCHAR(45) NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `delete_time` DATETIME NULL,
  PRIMARY KEY (`cid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
